import type { JointDefinition, JointGroup } from './types'

const DEG = Math.PI / 180

export const jointDefinitions: JointDefinition[] = [
  {
    id: 'torso_lift_joint',
    urdfNames: ['torso_lift_joint'],
    displayName: 'Torso Lift',
    group: 'torso',
    kind: 'prismatic',
    min: 0,
    max: 0.38615,
    home: 0.12,
    maxVelocity: 0.08,
    displayScale: 1,
    displayUnit: 'm',
    displayDecimals: 3,
  },
  {
    id: 'shoulder_pan_joint',
    urdfNames: ['shoulder_pan_joint'],
    displayName: 'Shoulder Pan',
    group: 'arm',
    kind: 'revolute',
    min: -1.6056,
    max: 1.6056,
    home: 0,
    maxVelocity: 55 * DEG,
    displayScale: 180 / Math.PI,
    displayUnit: '°',
    displayDecimals: 2,
  },
  {
    id: 'shoulder_lift_joint',
    urdfNames: ['shoulder_lift_joint'],
    displayName: 'Shoulder Lift',
    group: 'arm',
    kind: 'revolute',
    min: -1.221,
    max: 1.518,
    home: 0.2,
    maxVelocity: 50 * DEG,
    displayScale: 180 / Math.PI,
    displayUnit: '°',
    displayDecimals: 2,
  },
  {
    id: 'upperarm_roll_joint',
    urdfNames: ['upperarm_roll_joint'],
    displayName: 'Upper Arm Roll',
    group: 'arm',
    kind: 'revolute',
    min: -Math.PI,
    max: Math.PI,
    home: 0,
    maxVelocity: 80 * DEG,
    displayScale: 180 / Math.PI,
    displayUnit: '°',
    displayDecimals: 2,
  },
  {
    id: 'elbow_flex_joint',
    urdfNames: ['elbow_flex_joint'],
    displayName: 'Elbow Flex',
    group: 'arm',
    kind: 'revolute',
    min: -2.251,
    max: 2.251,
    home: 1.4,
    maxVelocity: 60 * DEG,
    displayScale: 180 / Math.PI,
    displayUnit: '°',
    displayDecimals: 2,
  },
  {
    id: 'forearm_roll_joint',
    urdfNames: ['forearm_roll_joint'],
    displayName: 'Forearm Roll',
    group: 'arm',
    kind: 'revolute',
    min: -Math.PI,
    max: Math.PI,
    home: 0,
    maxVelocity: 90 * DEG,
    displayScale: 180 / Math.PI,
    displayUnit: '°',
    displayDecimals: 2,
  },
  {
    id: 'wrist_flex_joint',
    urdfNames: ['wrist_flex_joint'],
    displayName: 'Wrist Flex',
    group: 'arm',
    kind: 'revolute',
    min: -2.16,
    max: 2.16,
    home: -0.6,
    maxVelocity: 90 * DEG,
    displayScale: 180 / Math.PI,
    displayUnit: '°',
    displayDecimals: 2,
  },
  {
    id: 'wrist_roll_joint',
    urdfNames: ['wrist_roll_joint'],
    displayName: 'Wrist Roll',
    group: 'arm',
    kind: 'revolute',
    min: -Math.PI,
    max: Math.PI,
    home: 0,
    maxVelocity: 100 * DEG,
    displayScale: 180 / Math.PI,
    displayUnit: '°',
    displayDecimals: 2,
  },
  {
    id: 'head_pan_joint',
    urdfNames: ['head_pan_joint'],
    displayName: 'Head Pan',
    group: 'head',
    kind: 'revolute',
    min: -1.57,
    max: 1.57,
    home: 0,
    maxVelocity: 60 * DEG,
    displayScale: 180 / Math.PI,
    displayUnit: '°',
    displayDecimals: 2,
  },
  {
    id: 'head_tilt_joint',
    urdfNames: ['head_tilt_joint'],
    displayName: 'Head Tilt',
    group: 'head',
    kind: 'revolute',
    min: -0.76,
    max: 1.45,
    home: 0.15,
    maxVelocity: 60 * DEG,
    displayScale: 180 / Math.PI,
    displayUnit: '°',
    displayDecimals: 2,
  },
  {
    id: 'gripper_opening',
    urdfNames: ['r_gripper_finger_joint', 'l_gripper_finger_joint'],
    displayName: 'Gripper Opening',
    group: 'gripper',
    kind: 'virtual',
    min: 0,
    max: 0.05,
    home: 0,
    maxVelocity: 0.025,
    displayScale: 1000,
    displayUnit: 'mm',
    displayDecimals: 1,
  },
]

export const groupedJointDefinitions = (group: JointGroup) =>
  jointDefinitions.filter((joint) => joint.group === group)

export const toDisplayValue = (joint: JointDefinition, internalValue: number) =>
  internalValue * joint.displayScale

export const toInternalValue = (joint: JointDefinition, displayValue: number) =>
  displayValue / joint.displayScale

export const getSimulationVelocity = (joint: JointDefinition) =>
  joint.simulationVelocity ?? joint.maxVelocity
